version: '3.8'

services:
  weather-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=4OyqH1LFvb3x0wsFrf4W7MTCgaEdln4ZOr9LpJSpPc1rhrLLl9ZWm3mUIb3WSP6hDCcEK3bbYmvKawXPR9vUWQ==
      - INFLUXDB_ORG=weather-org
      - INFLUXDB_BUCKET=weather-data
    depends_on:
      - influxdb
    volumes:
      - ./app:/app/app

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=weather-org
      - DOCKER_INFLUXDB_INIT_BUCKET=weather-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=4OyqH1LFvb3x0wsFrf4W7MTCgaEdln4ZOr9LpJSpPc1rhrLLl9ZWm3mUIb3WSP6hDCcEK3bbYmvKawXPR9vUWQ==
    volumes:
      - influxdb_data:/var/lib/influxdb2

volumes:
  influxdb_data:


